// Verilog netlist produced by program LSE 
// Netlist written on Wed Jan 22 11:59:38 2025
// Source file index table: 
// Object locations will have the form @<file_index>(<first_ line>[<left_column>],<last_line>[<right_column>])
// file 0 "f:/mysoftware/lattice/radiant/ip/avant/fifo/rtl/lscc_fifo.v"
// file 1 "f:/mysoftware/lattice/radiant/ip/avant/fifo_dc/rtl/lscc_fifo_dc.v"
// file 2 "f:/mysoftware/lattice/radiant/ip/avant/ram_dp/rtl/lscc_ram_dp.v"
// file 3 "f:/mysoftware/lattice/radiant/ip/avant/ram_dp_true/rtl/lscc_ram_dp_true.v"
// file 4 "f:/mysoftware/lattice/radiant/ip/avant/ram_dq/rtl/lscc_ram_dq.v"
// file 5 "f:/mysoftware/lattice/radiant/ip/avant/rom/rtl/lscc_rom.v"
// file 6 "f:/mysoftware/lattice/radiant/ip/common/adder/rtl/lscc_adder.v"
// file 7 "f:/mysoftware/lattice/radiant/ip/common/adder_subtractor/rtl/lscc_add_sub.v"
// file 8 "f:/mysoftware/lattice/radiant/ip/common/complex_mult/rtl/lscc_complex_mult.v"
// file 9 "f:/mysoftware/lattice/radiant/ip/common/counter/rtl/lscc_cntr.v"
// file 10 "f:/mysoftware/lattice/radiant/ip/common/distributed_dpram/rtl/lscc_distributed_dpram.v"
// file 11 "f:/mysoftware/lattice/radiant/ip/common/distributed_rom/rtl/lscc_distributed_rom.v"
// file 12 "f:/mysoftware/lattice/radiant/ip/common/distributed_spram/rtl/lscc_distributed_spram.v"
// file 13 "f:/mysoftware/lattice/radiant/ip/common/mult_accumulate/rtl/lscc_mult_accumulate.v"
// file 14 "f:/mysoftware/lattice/radiant/ip/common/mult_add_sub/rtl/lscc_mult_add_sub.v"
// file 15 "f:/mysoftware/lattice/radiant/ip/common/mult_add_sub_sum/rtl/lscc_mult_add_sub_sum.v"
// file 16 "f:/mysoftware/lattice/radiant/ip/common/multiplier/rtl/lscc_multiplier.v"
// file 17 "f:/mysoftware/lattice/radiant/ip/common/ram_shift_reg/rtl/lscc_shift_register.v"
// file 18 "f:/mysoftware/lattice/radiant/ip/common/subtractor/rtl/lscc_subtractor.v"
// file 19 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_add.v"
// file 20 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_addsub.v"
// file 21 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_complex_mult.v"
// file 22 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_counter.v"
// file 23 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_distributed_dpram.v"
// file 24 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_distributed_rom.v"
// file 25 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_distributed_shift_reg.v"
// file 26 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_distributed_spram.v"
// file 27 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_fifo.v"
// file 28 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_fifo_dc.v"
// file 29 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_mac.v"
// file 30 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_mult.v"
// file 31 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_multaddsub.v"
// file 32 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_multaddsubsum.v"
// file 33 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_ram_dp.v"
// file 34 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_ram_dp_be.v"
// file 35 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_ram_dp_true.v"
// file 36 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_ram_dq.v"
// file 37 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_ram_dq_be.v"
// file 38 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_rom.v"
// file 39 "f:/mysoftware/lattice/radiant/ip/pmi/pmi_sub.v"
// file 40 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/acc54.v"
// file 41 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/adc.v"
// file 42 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/alureg.v"
// file 43 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/aon.v"
// file 44 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bb_adc.v"
// file 45 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bb_cdr.v"
// file 46 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bb_i3c_a.v"
// file 47 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bb_programn.v"
// file 48 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bfd1p3kx.v"
// file 49 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bfd1p3lx.v"
// file 50 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/bnkref18.v"
// file 51 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/config_ip.v"
// file 52 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/config_lmmi.v"
// file 53 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/config_lmmia.v"
// file 54 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ddrdll.v"
// file 55 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/diffio18.v"
// file 56 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/dlldel.v"
// file 57 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/dp16k.v"
// file 58 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/dphy.v"
// file 59 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/dpsc512k.v"
// file 60 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/dqsbuf.v"
// file 61 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ebr.v"
// file 62 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/eclkdiv.v"
// file 63 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/eclksync.v"
// file 64 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/fbmux.v"
// file 65 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/fifo16k.v"
// file 66 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/i2cfifo.v"
// file 67 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ifd1p3bx.v"
// file 68 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ifd1p3dx.v"
// file 69 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ifd1p3ix.v"
// file 70 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ifd1p3jx.v"
// file 71 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/iologic.v"
// file 72 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/jtag.v"
// file 73 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/lram.v"
// file 74 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/m18x36.v"
// file 75 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mipi.v"
// file 76 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult18.v"
// file 77 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult18x18.v"
// file 78 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult18x36.v"
// file 79 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult36.v"
// file 80 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult36x36.v"
// file 81 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult9.v"
// file 82 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/mult9x9.v"
// file 83 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multaddsub18x18.v"
// file 84 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multaddsub18x18wide.v"
// file 85 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multaddsub18x36.v"
// file 86 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multaddsub36x36.v"
// file 87 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multaddsub9x9wide.v"
// file 88 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multiboot.v"
// file 89 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multpreadd18x18.v"
// file 90 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/multpreadd9x9.v"
// file 91 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ofd1p3bx.v"
// file 92 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ofd1p3dx.v"
// file 93 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ofd1p3ix.v"
// file 94 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/ofd1p3jx.v"
// file 95 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/osc.v"
// file 96 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/osca.v"
// file 97 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/oscd.v"
// file 98 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pcie.v"
// file 99 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pdp16k.v"
// file 100 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pdpsc16k.v"
// file 101 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pdpsc512k.v"
// file 102 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pll.v"
// file 103 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/plla.v"
// file 104 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pllrefcs.v"
// file 105 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/pmu.v"
// file 106 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/preadd9.v"
// file 107 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/refmux.v"
// file 108 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/reg18.v"
// file 109 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/sedc.v"
// file 110 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/seio18.v"
// file 111 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/seio33.v"
// file 112 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/sgmiicdr.v"
// file 113 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/siologic.v"
// file 114 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/sp16k.v"
// file 115 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/sp512k.v"
// file 116 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/tsalla.v"
// file 117 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/usb23.v"
// file 118 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/lifcl/wdt.v"
// file 119 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/dpr16x4.v"
// file 120 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/fd1p3bx.v"
// file 121 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/fd1p3dx.v"
// file 122 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/fd1p3ix.v"
// file 123 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/fd1p3jx.v"
// file 124 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/gsr.v"
// file 125 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/ib.v"
// file 126 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/ob.v"
// file 127 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/obz.v"
// file 128 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/pclkdivsp.v"
// file 129 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/spr16x4.v"
// file 130 "f:/mysoftware/lattice/radiant/cae_library/simulation/verilog/uaplatform/widefn9.v"

//
// Verilog Description of module MyOSC
// module wrapper written out since it is a black-box. 
//

//

module MyOSC (hf_out_en_i, hf_clk_out_o, lf_clk_out_o) /* synthesis cpe_box=1 */ ;
    input hf_out_en_i;
    output hf_clk_out_o;
    output lf_clk_out_o;
    
    
    
endmodule
