/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 1.3.1
    2024 11 11 10:36:22
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module MyADC (adc_en_i, adc_resetn_i, adc_clk_i, fab_clk_i, adc_cal_i,
    adc_soc_i, adc_calrdy_o, adc0_ch_sel_i, adc1_ch_sel_i, adc_cog_o,
    adc_eoc_o, adc_convstop_i, adc0_o, adc1_o, ADC_CP0, ADC_CN0, ADC_CP1,
    ADC_CN1, ADC_CP8, ADC_CN8, ADC_CP9, ADC_CN9)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  adc_en_i;
    input  adc_resetn_i;
    input  adc_clk_i;
    input  fab_clk_i;
    input  adc_cal_i;
    input  adc_soc_i;
    output  adc_calrdy_o;
    input  [3:0]  adc0_ch_sel_i;
    input  [3:0]  adc1_ch_sel_i;
    output  adc_cog_o;
    output  adc_eoc_o;
    input  adc_convstop_i;
    output  [11:0]  adc0_o;
    output  [11:0]  adc1_o;
    input  ADC_CP0;
    input  ADC_CN0;
    input  ADC_CP1;
    input  ADC_CN1;
    input  ADC_CP8;
    input  ADC_CN8;
    input  ADC_CP9;
    input  ADC_CN9;
endmodule